spring.application.name=api-gateway
server.port=${PORT:8085}

logging.level.org.springframework.cloud.gateway=DEBUG

# USER SERVICE
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=https://user-service-b2xn.onrender.com
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**,/api/admin/**,/api/users/**

# INTERVIEW SERVICE
spring.cloud.gateway.routes[1].id=interview-service
spring.cloud.gateway.routes[1].uri=https://interview-service-a90o.onrender.com
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/interviews/**,/api/resume/**


jwt.secret=${JWT_SECRET}


#Allow cross-origin to frontend to access urls

spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true

spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173,https://ai-interview-coach-platform.vercel.app
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true